### ISSUE TITLE
Kolokwium I dodanie pdfa

### ISSUE THREAD

**Issue by PiotrMakarewicz** [sszczep/WDI-2019#82]
Proszę o dodanie pdf'a z zadaniami z I kolokwium do tego folderu: github.com/sszczep/WDI-2019/tree/master/Kartk%C3%B3wki/2019-2020

[kol1.pdf](https://github.com/sszczep/WDI-2019/files/3995038/kol1.pdf)

**Comment by anuar2k** [comment]
Załatwione
